version: "3.8"
   
services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: userdjango
      MYSQL_PASSWORD: passworddjango
      MYSQL_DATABASE: django
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: iamroot
    restart:
      unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
    ports:
      - "3306:3306"
    networks:
      - backend

  web:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    volumes:
      - phpmyadmin:/var/www/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    expose:
      - '8080'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=iamroot 
    networks:
      - backend

  frontend:
    container_name: frontend
    image: httpd
    ports:
      - "80:80"
      - "443:443"
    expose: 
      - "80"
      - "443"
    volumes:
      - www:/var/www/html
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    links:
      - db
    networks:
      - frontend

volumes:
  db-data:
  www:
  phpmyadmin:

networks:
  backend:
  frontend: