# Generated by Django 3.2.9 on 2021-12-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=250)),
                ('imagen', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
