# Generated by Django 3.2.9 on 2021-12-07 13:29

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContenidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='categoria',
            field=models.CharField(choices=[('marvel', 'Marvel Studios'), ('dc', 'DC Cinematic Universe'), ('fox', '20 Century Fox'), ('wb', 'Warner Movies'), ('startrek', 'Star Treck Univese'), ('starwars', 'Star Wars Universe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='imagen',
            field=stdimage.models.StdImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='url',
            field=models.CharField(blank=True, default='../pages/player.html', max_length=250),
        ),
    ]
